/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaGrafica;
//import capalogica.Controladora;cuando se implememntecapa persistencia
import javax.swing.JOptionPane;

public class CargaDatos extends javax.swing.JFrame {
    //Controladora control=new Controladora();
     public void limpiar (){
 txtapedocente.setText("");
     txtcidocente.setText("");
     txtidgrupo.setText("");
     txtidmateria.setText("");
     txtnomdocente.setText("");
     txtnomgrupo.setText("");
     txtnommateria.setText("");
     txtteldocente.setText("");
     }
    public CargaDatos() {
        initComponents();
         setLocationRelativeTo(null);
         setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcidocente = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        txtapedocente = new javax.swing.JTextField();
        txtnomdocente = new javax.swing.JTextField();
        txtteldocente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidgrupo = new javax.swing.JTextField();
        txtnomgrupo = new javax.swing.JTextField();
        txtidmateria = new javax.swing.JTextField();
        txtnommateria = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel1.setText("                                                                                                        ALTA DE DATOS");

        jLabel2.setText("NOMBRE DOCENTE");

        txtcidocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcidocenteActionPerformed(evt);
            }
        });

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtapedocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapedocenteActionPerformed(evt);
            }
        });

        txtteldocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteldocenteActionPerformed(evt);
            }
        });

        jLabel3.setText("MATERIA");

        jLabel4.setText("ID GRUPO");

        txtnomgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomgrupoActionPerformed(evt);
            }
        });

        txtidmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidmateriaActionPerformed(evt);
            }
        });

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        jLabel5.setText("C.I DOCENTE");

        jLabel6.setText("APELLIDO DOCENTE");

        jLabel7.setText("TELEFONO DOCENTE");

        jLabel8.setText("NOMBRE MATERIA");

        jLabel9.setText("NOMBREGRUPO");

        btnatras.setText("ATRAS");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtapedocente, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnomdocente, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcidocente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtidmateria)
                                        .addComponent(txtteldocente, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtnommateria, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(txtnomgrupo)
                                        .addComponent(txtidgrupo))))
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnatras)
                        .addGap(42, 42, 42)
                        .addComponent(btnlimpiar)
                        .addGap(63, 63, 63)
                        .addComponent(btnguardar)))
                .addGap(186, 249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcidocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnomdocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtapedocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtteldocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtidmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnommateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtidgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlimpiar)
                            .addComponent(btnguardar)
                            .addComponent(btnatras))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomgrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomgrupoActionPerformed

    private void txtidmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidmateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidmateriaActionPerformed

    private void txtcidocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcidocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcidocenteActionPerformed

    private void txtapedocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapedocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapedocenteActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
     txtapedocente.setText("");
     txtcidocente.setText("");
     txtidgrupo.setText("");
     txtidmateria.setText("");
     txtnomdocente.setText("");
     txtnomgrupo.setText("");
     txtnommateria.setText("");
     txtteldocente.setText("");
     //esto es por si hay errores al ingresar datos y se dbe corregir mientras se da de alta
    
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtteldocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteldocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteldocenteActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
 if(txtapedocente.getText().isEmpty()||txtcidocente.getText().isEmpty()||txtidgrupo.getText().isEmpty()||txtidmateria.getText().isEmpty()
         ||txtnomdocente.getText().isEmpty()||txtnomgrupo.getText().isEmpty()||txtnommateria.getText().isEmpty()||txtteldocente.getText().isEmpty())  {
         JOptionPane.showMessageDialog(null, "Esos campos no pueden estar vacio");
     } else{
         String []dato=new String[8];
         dato[0]=txtcidocente.getText();
         dato[1]=txtnomdocente.getText();
         dato[2]=txtapedocente.getText();
         dato[3]=txtteldocente.getText();
         dato[4]=txtidmateria.getText();
         dato[5]=txtnommateria.getText();
         dato[6]=txtidgrupo.getText();
         dato[7]=txtnomgrupo.getText();
         
     }        
     limpiar();      
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        dispose();
        setVisible(false); 
        IguInicio ini=new IguInicio();
        ini.setVisible(true); 

        
        /*dispose();
        setVisible(false);
        principal prin=new principal();
        prin.setVisible(true);
        //estoy en voton volver de persona
        
        
        /*dispose();
        setVisible(false);
        Personas per=new Personas();
        per.setVisible(true);
        //estoy en ingreso de principal*/
        
    }//GEN-LAST:event_btnatrasActionPerformed
/* String cidoc = (String)txtcidocente.getText();
         String nomdoc=txtnomdocente.getText();
         String apedoc=txtapedocente.getText();
         String teldoc=(String)txtteldocente.getText();
         String idmate=txtidmateria.getText();
         String nomate=txtnommateria.getText();
         String idgrupo=txtidgrupo.getText();
         String nomgrupo=txtnomgrupo.getText();
         
         control.guardar(cidoc, nomdoc, apedoc, teldoc, idmate, nomate, idgrupo, nomgrupo);
       //esto queda para capa persistencia cuando se implemente*/
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapedocente;
    private javax.swing.JTextField txtcidocente;
    private javax.swing.JTextField txtidgrupo;
    private javax.swing.JTextField txtidmateria;
    private javax.swing.JTextField txtnomdocente;
    private javax.swing.JTextField txtnomgrupo;
    private javax.swing.JTextField txtnommateria;
    private javax.swing.JTextField txtteldocente;
    // End of variables declaration//GEN-END:variables
}
