/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaGrafica;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;



public class GestionFaltas extends javax.swing.JFrame {
    
    public DefaultTableModel modelo;
   
    
    
    public void limpiar (){
    cmbdocente.setSelectedIndex(0);
     cmbmateria.setSelectedIndex(0);
     cmbturno.setSelectedIndex(0);
     cmbgrupo.setSelectedIndex(0);
     cmbmotivo.setSelectedIndex(0);
     cmbhora.setSelectedIndex(0);
     txtinicio.getText();
     txtfin.getText(); 
    }
    

    /**
     * Creates new form GestionFaltas
     */
    public GestionFaltas() {
        
     
        
        initComponents();
        setLocationRelativeTo(null);
         setDefaultCloseOperation(0);
         
        modelo = new DefaultTableModel();
        modelo.addColumn("DOCENTE");
        modelo.addColumn("MATERIA");
        modelo.addColumn("TURNO");
        modelo.addColumn("GRUPO");
        modelo.addColumn("MOTIVO");
        modelo.addColumn("HORA");
        modelo.addColumn("INICIO");
        modelo.addColumn("FIN");
        this.tabla.setModel(modelo);
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbdocente = new javax.swing.JComboBox<>();
        cmbmateria = new javax.swing.JComboBox<>();
        cmbturno = new javax.swing.JComboBox<>();
        cmbgrupo = new javax.swing.JComboBox<>();
        cmbmotivo = new javax.swing.JComboBox<>();
        txtinicio = new javax.swing.JTextField();
        txtfin = new javax.swing.JTextField();
        btnatras = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncert = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        cmbhora = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("                               GESTION DE INASISTENCIAS ");

        cmbdocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCENTE", "Item 2", "Item 3", "Item 4" }));
        cmbdocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdocenteActionPerformed(evt);
            }
        });

        cmbmateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATERIA", "Item 2", "Item 3", "Item 4" }));

        cmbturno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURNO", "MAÑANA", "INTERMEDIO", "VESPERTINO", "NOCTURNO" }));

        cmbgrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRUPO", "Item 2", "Item 3", "Item 4" }));

        cmbmotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOTIVO", "LICENCIA MEDICA", "PARO", "OTRA" }));

        txtinicio.setText("INICIO");
        txtinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinicioActionPerformed(evt);
            }
        });

        txtfin.setText("FIN");
        txtfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinActionPerformed(evt);
            }
        });

        btnatras.setText("ATRAS");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncert.setText("ADJUNTAR CERTIFICADO");
        btncert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncertActionPerformed(evt);
            }
        });

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        cmbhora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HORA", "Item 2", "Item 3", "Item 4" }));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "DOCENTE", "MATERIA", "TURNO", "GRUPO", "MOTIVO", "HORA", "INICIO", "FIN"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnatras)
                                    .addComponent(cmbdocente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btneliminar))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncert)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbturno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(cmbgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btnguardar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(txtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbdocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnatras)
                    .addComponent(btneliminar)
                    .addComponent(btncert)
                    .addComponent(btnguardar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbdocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdocenteActionPerformed

    private void txtinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinicioActionPerformed

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
       dispose();
        setVisible(false); 
        IguInicio ini=new IguInicio();
        ini.setVisible(true); 
        
       
        
     
        
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed


        if(cmbdocente.getSelectedIndex()==0||cmbmateria.getSelectedIndex()==0||cmbturno.getSelectedIndex()==0||cmbgrupo.getSelectedIndex()==0
         ||cmbmotivo.getSelectedIndex()==0||cmbhora.getSelectedIndex()==0||txtinicio.getText().isEmpty()||txtfin.getText().isEmpty())  {
         JOptionPane.showMessageDialog(null, "Esos campos no pueden estar vacio");
       } else{
         String []dato=new String[8];
         dato[0]=(String) cmbdocente.getSelectedItem();
         dato[1]=(String) cmbmateria.getSelectedItem();
         dato[2]=(String) cmbturno.getSelectedItem();
         dato[3]=(String) cmbgrupo.getSelectedItem();
         dato[4]=(String) cmbmotivo.getSelectedItem();
         dato[5]=(String) cmbhora.getSelectedItem();
         dato[6]= txtinicio.getText();
         dato[7]= txtfin.getText();
         
         modelo.addRow(dato);
         
         
         
     }        
   // limpiar();              // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
   cmbdocente.setSelectedIndex(0);
     cmbmateria.setSelectedIndex(0);
     cmbturno.setSelectedIndex(0);
     cmbgrupo.setSelectedIndex(0);
     cmbmotivo.setSelectedIndex(0);
     cmbhora.setSelectedIndex(0);
     txtinicio.setText("");   
     txtfin.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfinActionPerformed

    private void btncertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncertActionPerformed
/*CargaDocumento pantalla4=new CargaDocumento();
        pantalla4.setVisible(true);
        pantalla4.setLocationRelativeTo(null);*/
        dispose();
        setVisible(false);
        CargaDocumento pantalla4=new CargaDocumento();
        pantalla4.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_btncertActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btncert;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cmbdocente;
    private javax.swing.JComboBox<String> cmbgrupo;
    private javax.swing.JComboBox<String> cmbhora;
    private javax.swing.JComboBox<String> cmbmateria;
    private javax.swing.JComboBox<String> cmbmotivo;
    private javax.swing.JComboBox<String> cmbturno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtfin;
    private javax.swing.JTextField txtinicio;
    // End of variables declaration//GEN-END:variables
}
